# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [4]:
import numpy as np

squaremeter = [1,1,1,1,1,1,1,1,1,1]
rooms = [2,2,2,2,2,2,2,2,2,2]
price = [3,3,3,3,3,3,3,3,3,3]

house_array = np.array ([squaremeter, rooms, price])
print(house_array)

print(house_array.shape)    # uc satir ve 10 sutundan olusan bir numpy arrayidir.

[[1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]]
(3, 10)


2. Transpose the array you have created, so that every line can represent features of one house.

[[1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]]


3. Display the shape of the array and explain what it means.

(3, 10)


In [5]:
array_ones = np.ones(30).reshape(6,5)

array_ones.shape[0]

list
for i in range(array_ones.shape[0]): and 
    i%2==0
    

SyntaxError: invalid syntax (<ipython-input-5-786534a5cd28>, line 6)

4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [11]:
import numpy as np


row = 6
col = 5

arr = np.ones((row, col))

for i in range(1, row, 2 ):
    for j in range (1, col, 2):
        arr[i, j] = 0
        
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1.]])