# <font color=blue>Assignments for "Mathematical Operations on NumPy Arrays"</font>

1. Load the array you saved in the previous lesson from the disk.

In [6]:
import numpy as np
last_arr1 = np.load("se_new_arr.npy")
last_arr1

array([[ 0.    ,  0.    ,  0.    ,  0.    ,  0.    ],
       [ 0.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 0.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 0.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 0.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 0.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 0.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 0.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 0.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 0.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 0.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 0.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 0.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 0.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 0.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 0.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 0.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 0.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 0.    , 35.7018, 28

2. Display the mean and the standard deviation for each column.

In [5]:
print(np.mean(last_arr,axis=0))
print(np.std(last_arr,axis=0))

[ 0.       35.36254  31.055145 18.9695    4.18    ]
[ 0.          8.16434915  9.00710837 18.78799683  1.0107423 ]


3. Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [7]:
last_arr2= np.array([1, 25, 25, 10, 4])
last_arr3= last_arr1 - last_arr2
print(last_arr3)

[[-1.00000e+00 -2.50000e+01 -2.50000e+01 -1.00000e+01 -4.00000e+00]
 [-1.00000e+00  1.24341e+01  1.08520e+01 -2.98000e+00  1.00000e-01]
 [-1.00000e+00  1.26878e+01  1.24016e+01  2.70000e-01  4.00000e-01]
 [-1.00000e+00  1.22003e+01  5.43760e+00  6.80700e+01  0.00000e+00]
 [-1.00000e+00  1.06846e+01  1.72660e+00  3.27700e+01  5.00000e-01]
 [-1.00000e+00  1.14171e+01  3.69910e+00  4.86000e+00  1.00000e-01]
 [-1.00000e+00  1.10535e+01  6.21350e+00  2.66800e+01  1.20000e+00]
 [-1.00000e+00  1.21958e+01  5.62410e+00  4.03300e+01  8.00000e-01]
 [-1.00000e+00  1.19653e+01  2.76330e+00 -3.07000e+00  3.00000e-01]
 [-1.00000e+00  1.38930e+01  1.44830e+00  1.62000e+00  2.00000e-01]
 [-1.00000e+00  1.23773e+01  1.13855e+01  5.30000e-01  8.00000e-01]
 [-1.00000e+00  1.08861e+01  1.06950e+00  1.84900e+01  9.00000e-01]
 [-1.00000e+00  1.24635e+01  1.13113e+01  5.29000e+00  3.00000e-01]
 [-1.00000e+00  1.20201e+01  1.10845e+01  0.00000e+00  1.00000e-01]
 [-1.00000e+00  1.26546e+01  1.66980e+00 -5.5000

4. Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [8]:
print(last_arr3*2)

[[-2.00000e+00 -5.00000e+01 -5.00000e+01 -2.00000e+01 -8.00000e+00]
 [-2.00000e+00  2.48682e+01  2.17040e+01 -5.96000e+00  2.00000e-01]
 [-2.00000e+00  2.53756e+01  2.48032e+01  5.40000e-01  8.00000e-01]
 [-2.00000e+00  2.44006e+01  1.08752e+01  1.36140e+02  0.00000e+00]
 [-2.00000e+00  2.13692e+01  3.45320e+00  6.55400e+01  1.00000e+00]
 [-2.00000e+00  2.28342e+01  7.39820e+00  9.72000e+00  2.00000e-01]
 [-2.00000e+00  2.21070e+01  1.24270e+01  5.33600e+01  2.40000e+00]
 [-2.00000e+00  2.43916e+01  1.12482e+01  8.06600e+01  1.60000e+00]
 [-2.00000e+00  2.39306e+01  5.52660e+00 -6.14000e+00  6.00000e-01]
 [-2.00000e+00  2.77860e+01  2.89660e+00  3.24000e+00  4.00000e-01]
 [-2.00000e+00  2.47546e+01  2.27710e+01  1.06000e+00  1.60000e+00]
 [-2.00000e+00  2.17722e+01  2.13900e+00  3.69800e+01  1.80000e+00]
 [-2.00000e+00  2.49270e+01  2.26226e+01  1.05800e+01  6.00000e-01]
 [-2.00000e+00  2.40402e+01  2.21690e+01  0.00000e+00  2.00000e-01]
 [-2.00000e+00  2.53092e+01  3.33960e+00 -1.1000